import java.awt.*;

public class Point1 {

//HUM ISS WINDOW ME EK NAYA CLASS LIKH SAKTE HAI(OR DUSRE WINDOWS ME BHI NO. OF CLASSES, DEPENDING UPON OUR REQUIREMENTS), NEW FIELDS AND METHODS KE SAATH.....AND THEN INN CLASS KO USE KARKE OBJECT CREATE KAR SAKTE HAI MAIN CLASS ME...
// .......PAR SAB CLASS KE OBJECT MAIN CLASS MEIN DECLARE HOGA OR OTHER CALCULATIONS WITH OBJECT WE DO SAB MAIN
 // CLASS ME HOGA AND THEN MAIN CLASS RUN HOTA HAI.......

}
